global:
  scrape_interval: 10s # How frequently to scrape targets by default.
  scrape_timeout: 5s # How long until a scrape request times out.
  evaluation_interval: 60s # How frequently to evaluate rules.

# A scrape configuration
scrape_configs:
  - job_name: karapace-registry
    metrics_path: /metrics
    static_configs:
      - targets:
        - karapace-registry:8081

  - job_name: karapace-rest
    metrics_path: /metrics
    static_configs:
      - targets:
        - karapace-rest:8082
