{
 "title": "Karapace",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Karapace Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Karapace Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "karapace_exceptions_total", "legendFormat": "{{where}} - {{exception}}" }
   ]
  },
  {
   "title": "Count by Exception",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "karapace_exceptions_sum_by_exception",
     "legendFormat": "exception={{exception}}"
    }
   ]
  },
  { "title": "Karapace HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "karapace_http_requests_total",
     "legendFormat": "instance={{instance}} method={{method}} path={{path}} status={{status}}"
    }
   ]
  },
  { "title": "Karapace Schema Reader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Subjects Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karapace_schema_reader_subjects{app=\"karapace-schema-registry\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schemas Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karapace_schema_reader_schemas{app=\"karapace-schema-registry\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Processed by Keymode",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karapace_schema_reader_records_processed_total",
     "legendFormat": "{{keymode}}"
    }
   ]
  },
  {
   "title": "Schema reader schema versions by state",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karapace_schema_reader_subject_data_schema_versions",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}