apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "karapace.fullname" .}}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "karapace.labels" . | nindent 4}}
data:
  config.yaml: |
    {{- toYaml .Values.karapace.config | nindent 4}}