apiVersion: v1
kind: Service
metadata:
  name: {{ include "karapace-registry.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "karapace-registry.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "karapace-registry.selectorLabels" . | nindent 4 }}
