StylesPath = ".vale/styles"

MinAlertLevel = warning

Packages = Google, proselint

[formats]
mdx = md

[*.md]
BasedOnStyles = Vale, Google, proselint, Karapace

# Disable Vale spelling in favour of our custom vocabulary and Google.
Vale.Spelling = No
Google.Spelling = Error

# Use our own heading style instead of Google's.
Google.Headings = No

Google.Quotes = No

# We use spaced em-dashes as house style.
Google.EmDash = No

# Formatting takes care of spacing.
Google.Spacing = No

Google.Colons = Error
Google.Exclamation = Warning
Google.Ordinal = Warning
Google.Units = Warning

proselint.DateMidnight = Warning
proselint.Typography = Warning
