"""
Copyright (c) 2023 Aiven Ltd
See LICENSE for details
"""
from enum import Enum
from http import HTTPStatus


class RESTErrorCodes(Enum):
    HTTP_BAD_REQUEST = HTTPStatus.BAD_REQUEST.value
    HTTP_NOT_FOUND = HTTPStatus.NOT_FOUND.value
    HTTP_INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR.value
    HTTP_UNPROCESSABLE_ENTITY = HTTPStatus.UNPROCESSABLE_ENTITY.value
    HTTP_SERVICE_UNAVAILABLE = HTTPStatus.SERVICE_UNAVAILABLE.value
    TOPIC_NOT_FOUND = 40401
    PARTITION_NOT_FOUND = 40402
    CONSUMER_NOT_FOUND = 40403
    UNKNOWN_TOPIC_OR_PARTITION = 40403
    UNSUPPORTED_FORMAT = 40601
    SCHEMA_RETRIEVAL_ERROR = 40801
    CONSUMER_ALREADY_EXISTS = 40902
    ILLEGAL_STATE = 40903
    INVALID_CONSUMER_PARAMETERS = 42204
    INVALID_DATA = 42205
    INVALID_VALUE = 50001
