name: Check schema compatibility

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check-generate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Need fetch-depth 0 to fetch tags, see https://github.com/actions/checkout/issues/701
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path:
            requirements.txt
      - name: Install libsnappy-dev
        run: sudo apt install libsnappy-dev
      - run: pip install -r requirements/requirements.txt
      # Compare with latest release when running on main.
      - run: make schema against=$(git describe --abbrev=0 --tags)
        if: github.ref == 'refs/heads/main'
      # Compare with main when running on branches/PRs.
      - run: make schema
        if: github.ref != 'refs/heads/main'
      - run: |
          diff=$(git --no-pager diff)
          if [[ ! -z "$diff" ]]; then
            echo "💥 Non-empty output from git diff, please run `make schema`."
            echo
            echo "$diff"
            exit 1
          else
            echo "✅ No diff after generating schema."
          fi
