name: Test Suite

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python -m pip install -r requirements-dev.txt

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
         version: '3.13.0'

    # needed by both unit and integation tests
    - name: Generate version.py
      run: make karapace/version.py

    - name: Execute unit-tests
      run: python3 -m pytest -s -vvv tests/unit/

    - name: Execute integration-tests
      run: python3 -m pytest -s -vvv tests/integration/ --log-dir=/tmp/ci-logs --log-file=/tmp/ci-logs/pytest.log

    - name: Archive logs
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
          name: logs
          # This directory is created by the fixture session_tmppath. The path is composed of a
          # prefix defined by --basepath, followed by a folder name, in this case it is "karapace".
          #
          # See:
          # - https://docs.pytest.org/en/6.2.x/tmpdir.html#base-temporary-directory
          # - fixture session_tmppath in tests/integration/conftest.py
          path: /tmp/pytest*
