name: Test Suite

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1
  PIP_PROGRESS_BAR: off
  PYTHONUNBUFFERED: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    env:
      PYTEST_ADDOPTS: >-
        --log-dir=/tmp/ci-logs
        --log-file=/tmp/ci-logs/pytest.log
        --showlocals
    steps:
    - uses: actions/checkout@v4
      # Need fetch-depth 0 to fetch tags, see https://github.com/actions/checkout/issues/701
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.0'

    - name: Resolve Karapace version
      run: echo KARAPACE_VERSION="$(git describe --tags | cut -d '-' -f -2 | sed 's/-/.dev/g')" >> $GITHUB_ENV

    - run: echo "RUNNER_UID=$(id -u)" >> $GITHUB_ENV
    - run: echo "RUNNER_GID=$(id -g)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache docker layers
      uses: docker/build-push-action@v4
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
        KARAPACE_VERSION: ${{ env.KARAPACE_VERSION }}
        PR_TAG: aiven-open/karapace-pr:${{ env.KARAPACE_VERSION }}
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ env.PR_TAG }}
        push: false
        build-args: |
          KARAPACE_VERSION=${{ env.KARAPACE_VERSION }}
          PYTHON_VERSION=${{ matrix.python-version }}
        file: container/Dockerfile
        platforms: linux/amd64

    - run: make unit-tests-in-docker
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
        KARAPACE_VERSION: ${{ env.KARAPACE_VERSION }}
        RUNNER_UID: ${{ env.RUNNER_UID }}
        RUNNER_GID: ${{ env.RUNNER_GID }}
        COVERAGE_FILE: "/opt/karapace/coverage/.coverage.${{ matrix.python-version }}"
        PYTEST_ARGS: "--cov=karapace --cov=schema_registry --cov-append --numprocesses 4"

    - run: make e2e-tests-in-docker
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
        KARAPACE_VERSION: ${{ env.KARAPACE_VERSION }}
        RUNNER_UID: ${{ env.RUNNER_UID }}
        RUNNER_GID: ${{ env.RUNNER_GID }}
        COVERAGE_FILE: "/opt/karapace/coverage/.coverage.${{ matrix.python-version }}"
        PYTEST_ARGS: "--cov=karapace --cov=schema_registry --cov-append --numprocesses 4"

    - run: make integration-tests-in-docker
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
        KARAPACE_VERSION: ${{ env.KARAPACE_VERSION }}
        RUNNER_UID: ${{ env.RUNNER_UID }}
        RUNNER_GID: ${{ env.RUNNER_GID }}
        COVERAGE_FILE: "/opt/karapace/coverage/.coverage.${{ matrix.python-version }}"
        PYTEST_ARGS: "--cov=karapace --cov=schema_registry --cov-append --random-order --numprocesses 4"

    - name: Archive logs
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: karapace-integration-test-logs-${{ matrix.python-version }}
        path: /tmp/ci-logs

    - name: Archive coverage file
      uses: actions/upload-artifact@v4
      with:
        name: "coverage-${{ matrix.python-version }}"
        path: ".coverage.${{ matrix.python-version }}"
        include-hidden-files: true

  coverage:
    name: Coverage report
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@v4

    - run: make install-dev

    - name: Download coverage
      id: download_coverage
      uses: actions/download-artifact@v4
      with:
        pattern: coverage-*
        merge-multiple: true

    - name: Post coverage comment
      id: post_coverage_comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_COVERAGE_FILES: true

    - name: Store PR comment to be posted
      uses: actions/upload-artifact@v4
      if: steps.post_coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
      with:
        name: python-coverage-comment-action
        path: python-coverage-comment-action.txt
