name: Test Suite

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1
  PIP_PROGRESS_BAR: off
  PYTHONUNBUFFERED: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: ${{ matrix.python-version }}

    - run: make install version
    - run: make unit-tests
    - run: make integration-tests
      env:
        PYTEST_ARGS: --log-dir=/tmp/ci-logs --log-file=/tmp/ci-logs/pytest.log

    - name: Archive logs
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: karapace-integration-test-logs-${{ matrix.python-version }}
        path: /tmp/ci-logs
