name: Test Suite

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install libsnappy-dev (python-snappy legacy-install-failure on Python 3.11)
      run: sudo apt install libsnappy-dev

    - name: Install dependencies
      run: python -m pip install -r requirements-dev.txt

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
         version: '3.13.0'
         repo-token: ${{ secrets.GITHUB_TOKEN }}

    # needed by both unit and integation tests
    - name: Generate version.py
      run: make karapace/version.py

    - name: Execute unit-tests
      timeout-minutes: 2
      run: python3 -m pytest -s -vvv tests/unit/

    - name: Execute integration-tests
      timeout-minutes: 15
      run: python3 -m pytest -s -vvv tests/integration/ --log-dir=/tmp/ci-logs --log-file=/tmp/ci-logs/pytest.log

    - name: Archive logs
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
          name: logs  ${{ matrix.python-version }}
          path: /tmp/ci-logs
